name: Example Reusable action 
description: Giving it a try

runs:
    using: composite
    steps:
        - shell: bash
          run: |
            cat > testmo-resources.json <<EOF
            {
            "fields": [
                { "name": "repo",         "type": "string", "value": "${github.repo}" },
                { "name": "branch",       "type": "string", "value": "${github.ref}" },
                { "name": "commit",       "type": "string", "value": "${github.sha}" },
                { "name": "author",       "type": "string", "value": "${github.triggering_actor}" },
                { "name": "message",      "type": "string", "value": "$(git log -1 --pretty=%s)" },
                { "name": "timestamp",    "type": "string", "value": "$(git log -1 --pretty=%ci)" },
                { "name": "attempt",      "type": "string", "value": "${github.run_attempt}" },
                { "name": "run-id",       "type": "string", "value": "${github.run_id}" },
                { "name": "language",     "type": "string", "value": "${{ inputs.language }}" },
                { "name": "test-tooling", "type": "string", "value": "${{ inputs.test_tooling }}" }
            ],
            "links": [
                {
                "name": "github-run",
                "url": "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
                }
            ]
            }
            EOF

            cat testmo-resources.json
