name: "test"
run-name: "testing"

on: [push]

jobs:
    Exploring-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

    Test-2:
      uses: ./.github/workflows/testmo.yml
            