name: "test"
run-name: "testing"

on: [push]

jobs:
    Exploring-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - uses: abatilo/actions-poetry@v3.0.2
            - run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
            - run: poetry -C battle-ship install
            - run: poetry -C battle-ship run pytest